version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    command: -p 5432
